//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWpfApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Completed_orders = new HashSet<Completed_orders>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int id_book { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string cipher_ISBN { get; set; }
        public string classification_BBK { get; set; }
        public string publishing { get; set; }
        public string place_of_publication { get; set; }
        public Nullable<System.DateTime> year_of_publication { get; set; }
        public string number_of_pages { get; set; }
        public string genre { get; set; }
        public Nullable<int> id_bookbinding { get; set; }
        public string language { get; set; }
        public Nullable<int> id_status { get; set; }
        public string description { get; set; }
        public byte[] book_image { get; set; }
    
        public virtual Bookbinding Bookbinding { get; set; }
        public virtual Status_book Status_book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Completed_orders> Completed_orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
