//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWpfApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_order { get; set; }
        public int id_book { get; set; }
        public int id_library_card { get; set; }
        public System.DateTime issue_date { get; set; }
        public System.DateTime return_date { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Library_card Library_card { get; set; }
    }
}
