//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryWpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2;2;Естественные науки
        ///20;20;Естественные науки в целом
        ///20г;20г;История естественных наук в целом
        ///20.1;20.1;Экология
        ///20.18;20.18;Экологическая защита и охрана окружающей среды
        ///20.3;20.3;Аномальные явления в окружающей среде. Уфология
        ///22;22;Физико-математические науки
        ///22.1;22.1;Математика
        ///22.1г;22.1г;История математики
        ///22.12;22.12;Основания математики. Математическая логика
        ///22.13;22.13;Теория чисел
        ///22 130;22 130;Арифметика
        ///22 131;22 131;Элементарная теория чисел
        ///22 132;22 132;Алгебраическая теор [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BBK {
            get {
                return ResourceManager.GetString("BBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cпецслужбы
        ///Автомобили и ПДД
        ///Альтернативная история
        ///Альтернативная медицина
        ///Анекдоты
        ///Антисоветская литература
        ///Античная литература
        ///Архитектура
        ///Астрология
        ///Астрономия и Космос
        ///Афоризмы
        ///Базы данных
        ///Банковское дело
        ///Басни
        ///Биографии и мемуары
        ///Биология
        ///Биофизика
        ///Боевая фантастика
        ///Боевики
        ///Боевые искусства
        ///Ботаника
        ///Былины
        ///Верлибры
        ///Вестерны
        ///Ветеринария
        ///Визуальная поэзия
        ///Внешнеэкономическая деятельность
        ///Водевиль
        ///Военная документалистика
        ///Военная история
        ///Военная проза
        ///Военное дело
        ///Газеты и  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0;английский
        ///1;английский
        ///2;Французский
        ///3;Немецкий
        ///4;Япония
        ///5;Бывший СССР
        ///600;Иран
        ///601;Казахстан
        ///602;Индонезия
        ///603;Саудовская Аравия
        ///604;Вьетнам
        ///605;Индюк
        ///606;Румыния
        ///607;Мексика
        ///608;Северная Македония
        ///609;Литва
        ///610;Нераспределенный
        ///611;Таиланд
        ///612;Перу
        ///613;Маврикий
        ///614;Ливан
        ///615;Венгрия
        ///616;Таиланд
        ///617;Украина
        ///618;Греция
        ///619;Болгария
        ///620;Маврикий
        ///621;Филиппины
        ///622;Иран
        ///623;Индонезия
        ///624;Шри-Ланка
        ///625;Индюк
        ///626;Нераспределенный
        ///627;Нераспределенный
        ///628;Нераспределенный
        ///629 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ISBNRegGroups {
            get {
                return ResourceManager.GetString("ISBNRegGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абазинский язык
        ///Абенаки
        ///Абхазский язык
        ///Аварский язык
        ///Авестийский язык
        ///Авнги
        ///Агульский язык
        ///Адыгейский язык
        ///Азербайджанский язык
        ///Аймара
        ///Айнийский язык
        ///Айнский язык
        ///Аканский язык
        ///Аккадский язык
        ///Алабамский язык
        ///Албанский язык
        ///Алеутский язык
        ///Алжирский язык
        ///Алтайский язык
        ///Амаракери
        ///Амисский язык
        ///Амхарский язык
        ///Английский язык
        ///Англосаксонский язык
        ///Андийский язык
        ///Анута
        ///Апачский язык
        ///Арабела
        ///Арабский язык
        ///Арагонский язык
        ///Арамейский язык
        ///Аранский язык
        ///Аранта
        ///Арапахо
        ///Аргобба
        ///Армянск [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
    }
}
